name = "github-oauth-app-hello-world"
main = "src/index.ts"
compatibility_date = "2025-03-03"

[observability]
enabled = true

[vars]
GITHUB_REDIRECT_URI = "https://github-oauth-app-hello-world.tmfam.workers.dev/callback"
